# site settings
title: Eric Bello
subtitle: 
email: ericnbello@icloud.com
description: Personal website showcasing various IT projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericnbello.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: Miami
state: FL
zip_code: 33155
country: United States of America
phone: (305) 981-6595

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ericnbello
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/ericnbello
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
